# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven - Publish steplogs-spring-rmi-http to GitHub Packages Apache Maven

on:
  push:
    tags:
      - '*'
  workflow_dispatch:  # This enables the manual trigger from the GitHub UI

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    - name: Extract Git Tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "Latest Git Tag: $latest_tag"  # This prints the latest tag
        echo "TAG_NAME=$latest_tag" >> $GITHUB_ENV  # Set it as an environment variable
        
    - name: Set up JDK 17.0.14+7
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.14+7'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots clean package
      
    - name: Publish steplogs-spring-rmi-http to GitHub Packages Apache Maven
      run: mvn --batch-mode clean deploy versions:set -DnewVersion=${{ env.TAG_NAME }} -s ./settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PUBLISH_GITHUB_TOKEN }}
        TAG_NAME: ${{ env.TAG_NAME }}
  
